# Generated by Django 3.1 on 2020-08-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='profile_pics/nodetail.jpg', null=True, upload_to='profile_pics/')),
                ('name', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_phone', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=9, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=16)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('Class', models.CharField(max_length=1)),
                ('year', models.IntegerField()),
                ('bus_no', models.CharField(max_length=3)),
                ('address1', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.departmentmodel')),
            ],
        ),
    ]
